site:
  title: ownCloud Desktop Client Documentation

content:
  sources:
  - url: ../
    branches: [HEAD,2.6]
    start_path: docs/

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
