name: Build with conan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure environment and install Conan release
      run: |
        apt-get update && apt-get install -y python3 python3-pip
        python3 -m pip install conan

    - name: Run example with latest Conan release
      shell: bash
      run: |
        conan profile detect
        conan install . --output-folder=build --build=missing
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build .


  