name: ownCloud CI

on: 
  pull_request:
    branches:
      - "master"
      - "2.7"
    
  push:
    branches:
      - "master"
      - "2.7"

defaults:
  run:
    shell: pwsh

jobs:
# ------------------------------------------------------------------------------------------------------------------------------------------
  build:
    name: Build ownCloud
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            include:
            - target: windows-msvc2017_32-cl
              os: windows-latest
              python: py
            - target: windows-msvc2017_64-cl
              os: windows-latest
              python: py
            - target: macos-64-clang
              os: macos-latest
              python: python3
    env:
      CRAFT: ${{ matrix.python }} "${{ github.workspace }}/CraftMaster/CraftMaster/CraftMaster.py" --config "${{ github.workspace }}/.craft.ini" --target ${{ matrix.target }} --variables "WORKSPACE=${{ github.workspace }}" -c

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: true

    - name: Clone CraftMaster
      run: git clone --depth=1 https://invent.kde.org/kde/craftmaster.git "${{ github.workspace }}/CraftMaster/CraftMaster"

    - name: Craft unshelve
      run:  Invoke-Expression "$env:CRAFT --unshelve `"${{ github.workspace }}/.craft.shelf`" "

    - name: Install NSIS
      run: Invoke-Expression "$env:CRAFT dev-utils/nsis"

    - name: Install dependencies
      run: Invoke-Expression "$env:CRAFT --install-deps owncloud/owncloud-client"

    - name: Build
      run: Invoke-Expression "$env:CRAFT --no-cache --src-dir `"${{ github.workspace }}`" owncloud/owncloud-client"

    - name: Run tests
      run: Invoke-Expression "$env:CRAFT --no-cache --src-dir `"${{ github.workspace }}`" --test owncloud/owncloud-client"

    - name: Package
      run: if ($IsWindows) { Invoke-Expression "$env:CRAFT --no-cache --src-dir `"${{ github.workspace }}`" --package owncloud/owncloud-client" } else {Write-Host "Skip packaging on mac as the build gets stuck when mounting"}

    - name: Update shelf
      run: |
        New-Item -ItemType Directory "${{ github.workspace }}/binaries/" -ErrorAction SilentlyContinue
        Invoke-Expression "$env:CRAFT --shelve `"${{ github.workspace }}/.craft.shelf`" "
        Copy-Item "${{ github.workspace }}/.craft.shelf" "${{ github.workspace }}/binaries/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} - ${{ matrix.target }}
        path: ${{ github.workspace }}/binaries/*



