name: ownCloud CI

on: 
  pull_request:
    branches:
      - "master"
      - "2.7"
    
  push:
    branches:
      - "master"
      - "2.7"

defaults:
  run:
    shell: pwsh

jobs:
# ------------------------------------------------------------------------------------------------------------------------------------------
  build-windows:
    name: Windows
    runs-on: windows-latest
    strategy:
        matrix:
            target: ["windows-msvc2017_32-cl", "windows-msvc2017_64-cl"]
    env:
      WORKSPACE: ${{ github.workspace }}
      CRAFT: C:/CraftMaster/${{ matrix.target }}/craft/bin/craft.py

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: true

    - name: Clone CraftMaster
      run: git clone --depth=1 https://invent.kde.org/kde/craftmaster.git C:/CraftMaster/CraftMaster

    - name: Configure CraftMaster
      run: py C:/CraftMaster/CraftMaster/CraftMaster.py --config $env:WORKSPACE/.craft.ini --variables "WORKSPACE=$env:WORKSPACE"

    - name: Craft unshelve
      run: py $env:CRAFT --unshelve $env:WORKSPACE/.craft.shelf

    - name: Install NSIS
      run: py $env:CRAFT dev-utils/nsis

    - name: Install dependencies
      run: py $env:CRAFT --install-deps owncloud/owncloud-client

    - name: Build
      run: py $env:CRAFT --no-cache --src-dir $env:WORKSPACE owncloud/owncloud-client

    - name: Run tests
      run: py $env:CRAFT --no-cache --src-dir $env:WORKSPACE --test owncloud/owncloud-client

    - name: Package
      run: py $env:CRAFT --no-cache --src-dir $env:WORKSPACE --package owncloud/owncloud-client

    - name: Update shelf
      run: |
        py $env:CRAFT --shelve $env:WORKSPACE/.craft.shelf
        Copy-Item $env:WORKSPACE/.craft.shelf $env:WORKSPACE/binaries/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: ${{ github.workspace }}/binaries/*



